use crate::*;
use bevy::input::mouse::MouseWheel;
use bevy_mod_picking::events::{Click, Out, Over, Pointer};
use bevy_mod_picking::prelude::On;
use bevy_mod_picking::PickableBundle;
use rand::{thread_rng, Rng};
use std::collections::HashMap;
use std::f32;

pub struct MapPlugin;

impl Plugin for MapPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(OnEnter(GameState::GenerateMap), generate_map)
            .add_systems(OnEnter(GameState::Map), make_map)
            .add_systems(
                Update,
                (scroll).distributive_run_if(in_state(GameState::Map)),
            )
            .add_systems(OnExit(GameState::Map), clean_up);
    }
}

#[derive(Resource, Default, Reflect)]
pub struct MapManager {
    map_data: Option<HashMap<Tile, Vec<(i32, i32)>>>,
    pub current_tile: (i32, i32),
}

#[derive(Component)]
struct MapThing;

fn clean_up(mut commands: Commands, map_things: Query<Entity, With<MapThing>>) {
    for map_thing in &map_things {
        commands.entity(map_thing).despawn_recursive()
    }
}

#[derive(Eq, Hash, PartialEq, Reflect, Clone, Copy)]
struct Tile {
    pos: (i32, i32),
    tile_type: GameState,
}
/*
Converted proof of concept Python Script to Rust with GPT 4 (generate_map_data + add_connections)
The code works by generating 2 paths through the map as seen in line []
I chose to do this so that the player has agency in deciding their path, without having to spend time on verifying whether there is a possible path
The paths are generated by the following logic:

The path starts at y=0, x ∈ [0, 4], letting `current_tile` be that value
From there, a tile which is at most 1 left or right of the `current_tile` and 1 above it is randomly generated, its position stored in `new_tile`
This connection is added to the connections variable via `add_connection`
The value of `current_tile` is set to `new_tile` and the process is repeated until the y value of `current_tile` is 1 less than `START_TILE`
Instead of generating a new `new_tile`, `new_tile` just becomes `START_TILE`, reasonging explained later

This conlcudes the creating of 1 path. This process is repeated again, for the second path.

The player starts at the start tile, so all paths are generated such that they end with the final node being the start tile
This is done to enable the player to enter the game from their start tile


creating a Hshmap of StartTile: Tile, ConnectingLocations: Vec<(i32, i32)>
This allows one tile to be connected to multiple other tiles
*/

fn generate_map_data() -> HashMap<Tile, Vec<(i32, i32)>> {
    let mut connections: HashMap<Tile, Vec<(i32, i32)>> = HashMap::new();
    let mut rng = thread_rng();

    for _ in 0..3 {
        let mut current_tile_pos = (rng.gen_range(0..=4), 0);
        let mut current_tile: Tile = Tile {
            pos: current_tile_pos,
            tile_type: select_tile_type(current_tile_pos.1),
        };
        for _ in 0..(START_TILE.1 - 1) {
            let new_tile = (
                rng.gen_range((current_tile_pos.0 - 1).max(0)..=(current_tile_pos.0 + 1).min(4)),
                current_tile_pos.1 + 1,
            );
            add_connection(&mut connections, current_tile, new_tile);
            current_tile_pos = new_tile;
            current_tile = Tile {
                pos: current_tile_pos,
                tile_type: select_tile_type(current_tile_pos.1),
            };
        }
        add_connection(&mut connections, current_tile, START_TILE)
    }

    connections
}

fn add_connection(
    connections: &mut HashMap<Tile, Vec<(i32, i32)>>,
    from_tile: Tile,
    to_tile: (i32, i32),
) {
    connections
        .entry(from_tile)
        .or_insert_with(Vec::new)
        .push(to_tile);
}

fn select_tile_type(floor: i32) -> GameState {
    if floor < 5 {
        let mut rng = thread_rng();
        let num: f64 = rng.gen();
        if num > 0.8 {
            GameState::RestSite
        } else {
            GameState::Combat
        }
    } else {
        GameState::Combat
    }
}

fn generate_map(mut commands: Commands, mut next_state: ResMut<NextState<GameState>>) {
    commands.insert_resource(MapManager {
        map_data: Some(generate_map_data()),
        current_tile: START_TILE,
    });
    next_state.set(GameState::Map);
}

/*
The least intuitive part of `make_map()` is that the tile connections are read in the form of `end_tile`, `Vec<start_tile>`
That is, this structure would be stored as A: [B, C]
                        +-----+ +-----+
                        |  B  | |  C  |
                        |     | |     |
                        +-----+ +-----+
                           \      /
                            \    /
                             \  /
                              \/
                            +-----+
                            |  A  |
                            |     |
                            +-----+
For spawning the tiles, it is easier to work with a different layout because
When a tile is spawned it is either active or inactive
The activity state is determined by cycling through the start tiles and seeing if one of them matches the tile the player is currently on
In the above example, when determining the activity status of tile A, the algorithm check whether the positions of tile B OR C match the player's current position (stored in the combat manager)
*/

fn make_map(
    mut commands: Commands,
    map_manager: ResMut<MapManager>,
    asset_server: Res<AssetServer>,
) {
    let map_data = map_manager.map_data.clone().unwrap();
    let current_tile = map_manager.current_tile.clone();

    let mut generated_tiles: Vec<Tile> = Vec::new();
    for (end_tile, start_tiles) in map_data {
        let x1 = end_tile.pos.0 as f32 * 230. - 460.;
        let y1 = (end_tile.pos.1 - current_tile.1 + 2) as f32 * 300. - 300.;
        for start_tile in &start_tiles {
            let x2 = start_tile.0 as f32 * 230.0 - 460.;
            let y2 = (start_tile.1 - current_tile.1 + 2) as f32 * 300. - 300.;

            let height = ((x1 - x2).powf(2.) as f32 + (y1 - y2 + 100.).powf(2.) as f32).sqrt();
            let angle = (-(x2 - x1) / (y2 - y1 - 100.)).atan();
            // Connecting Rod
            commands
                .spawn(SpriteBundle {
                    sprite: Sprite {
                        color: Color::GRAY,
                        custom_size: Some(Vec2::new(5.0, height)),
                        ..default()
                    },
                    transform: Transform::from_xyz((x1 + x2) / 2.0, (y1 + y2) / 2.0, 0.)
                        .with_rotation(Quat::from_rotation_z(angle)),
                    ..Default::default()
                })
                .insert(MapThing)
                .insert(Name::new("Connecting Rod"));
            if !generated_tiles.contains(&end_tile) {
                spawn_tile(
                    &mut commands,
                    (x1, y1),
                    &current_tile,
                    &start_tiles,
                    &end_tile,
                    &asset_server,
                );
                generated_tiles.push(end_tile);
            }
        }
    }
}

fn spawn_tile(
    commands: &mut Commands,
    pos: (f32, f32),
    current_tile: &(i32, i32),
    start_tiles: &Vec<(i32, i32)>,
    spawning_tile: &Tile,
    asset_server: &Res<AssetServer>,
) {
    let image: Handle<Image>;
    match spawning_tile.tile_type {
        GameState::Combat => image = asset_server.load("icons/combat.png"),
        GameState::RestSite => image = asset_server.load("icons/rest_site.png"),
        _ => image = asset_server.load("icons/placeholder.png"),
    }
    let bundle = SpriteBundle {
        texture: image,
        sprite: Sprite {
            color: Color::DARK_GRAY,
            custom_size: Some(Vec2::new(100., 100.)),
            ..default()
        },
        transform: Transform::from_xyz(pos.0, pos.1, 0.),
        ..Default::default()
    };
    let mut binding = commands.spawn(bundle);
    let spawn = &mut binding.insert(Name::new("Encounter"));
    let tile = spawn.insert(MapThing);
    let tile_type = spawning_tile.tile_type;
    let c_tile = spawning_tile.pos;
    for start_tile in start_tiles {
        if current_tile == start_tile {
            tile.insert(Sprite {
                color: Color::GRAY,
                custom_size: Some(Vec2::new(100., 100.)),
                ..default()
            });
            tile.insert(PickableBundle::default());
            tile.insert(On::<Pointer<Click>>::run(
                move |mut next_state: ResMut<NextState<GameState>>,
                      mut map_manager: ResMut<MapManager>| {
                    next_state.set(tile_type);
                    map_manager.current_tile = c_tile
                },
            ));
            tile.insert(On::<Pointer<Over>>::target_component_mut::<Sprite>(
                |_, sprite| {
                    sprite.color.set_l(1.);
                },
            ));
            tile.insert(On::<Pointer<Out>>::target_component_mut::<Sprite>(
                |_, sprite| {
                    // debug!("{}", sprite.color.l())
                    sprite.color.set_l(0.5);
                },
            ));
            break;
        }
    }
}

fn scroll(
    mut mouse_wheel_events: EventReader<MouseWheel>,
    mut query: Query<&mut Transform, With<MapThing>>,
) {
    for event in mouse_wheel_events.read() {
        for mut transform in query.iter_mut() {
            // Adjust this value to control the zoom speed
            let scroll_speed = -0.3;
            let scroll_amount = 1.0 + event.y * scroll_speed;

            // Scale the camera transform to zoom
            transform.translation += Vec3::new(0.0, scroll_amount, 0.0);
            // if transform.translation.y < -150.0 {
            //     transform.translation.y = -150.0
            // } else if transform.translation.y > 3300.0 {
            //     transform.translation.y = 3300.0
            // }
        }
    }
}
